name: Building
on: [push] #Cuando se ejecuta
jobs:
  building: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copiamos el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      # - run: python my_script.py
