name: Building
run-name: ${{ github.actor }} is testing Building yml
on: [push] #Cuando se ejecuta
# on:
#   push: #Esto se ejecuta solo cuando hay un tag
#     tags:
#       - "v*.*.*"
jobs:
  building: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Copiamos el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: install dependencies
        run: poetry install
      - name: Testing
        run: poetry run pytest --junitxml=jest-junit.xml
      - name: Building
        run: poetry build #BUILDING
      - name: Publish Release  to GH
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests with reports            # Name of the check run which will be created
          path: jest-junit.xml    # Path to test results
          reporter: java-junit        # Format of test results
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: htmlcov/index.html
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      
      
      # - uses: actions/upload-artifact@v2  # upload test results
      #   if: success() || failure()        # run this step even if previous step failed
      #   with:
      #     name: test-results
      #     path: jest-junit.xml